### ISSUE TITLE
Weird framework naming [in docs]

### ISSUE THREAD

**Issue by Jeehut** [skyweb07/Snap.swift#33]
I find it pretty weird to import something with an underscore in Swift. I'm switching over from FBSnapshotTestcase to Snap.swift mainly because this library is written in Swift (not Objective-C) – but this line makes me really feel like it's not designed for Swift at all:

```
import Snap_swift
```

Couldn't we rename the library to what it should be named, just `Snap`? Even the project file is `Snap` and seeing `Snap.swift` as a file whose name is `Snap` also implies the library should be called `Snap`.

I would even find `SnapDotSwift` or `SnapSwift` better then `Snap_swift`.

**Comment by Jeehut** [comment]
Ah, I just saw that the built framework actually is already named `Snap`. Maybe it's just the documentation which is outdated?

**Comment by skyweb07** [comment]
Yep, the problem is Cocoapods, there was another library called Snap so I couldn't have the same name that's why I selected the Snap.swift one, when we send the lib to CP repo it actually uses that name cause how internally works, I know it's a pain and not pretty but I don't know if we can set a library name that's not the actual Snap_Swift on CP, for Carthage works just ok because it's getting the actual framework name

**Comment by Jeehut** [comment]
The `module_name` setting is your friend:
https://guides.cocoapods.org/syntax/podspec.html#module_name

😉

**Comment by skyweb07** [comment]
Holy cow! I didn't know about that property, I think I'll update it ASAP, the only problem is that's a breaking change so I'll have to bump the actual version to 1.0.0. Thank you mate!!!

**Comment by Jeehut** [comment]
Glad I could help. ^^
